### ISSUE TITLE
dont find aagcn

### ISSUE THREAD

**Issue by ziguozhao** [BinLiang-NLP/AAGCN-ACSA#2]
![image](https://user-images.githubusercontent.com/77605566/144994190-b2e2a754-de72-4d98-bbcf-a98addf73ea4.png)

**Comment by BinLiang-NLP** [comment]
> ![image](https://user-images.githubusercontent.com/77605566/144994190-b2e2a754-de72-4d98-bbcf-a98addf73ea4.png)

Sorry for the error of file names.
I have fixed the errors.
Please use "git pull" to update them or change "intergcn" to "aagcn".
Thanks a lot!
