### ISSUE TITLE
Why not transformers instead of pytorch_pretrained_bert 

### ISSUE THREAD

**Issue by shenjing023** [BinLiang-NLP/AAGCN-ACSA#4]
If I use transformers instead of pytorch_pretrained_bert, there are something error:
```python
# aagcn_bert.py#56
# encoder_layer, pooled_output = self.bert(
#     text_bert_indices, token_type_ids=bert_segments_ids, output_all_encoded_layers=False)
 output = self.bert(
            text_bert_indices, token_type_ids=bert_segments_ids, return_dict=False)
 text_out = output[0]
```
And the error is:
```
Traceback (most recent call last):
  File "train_bert.py", line 338, in <module>
    main()
  File "train_bert.py", line 333, in main
    ins.run()
  File "train_bert.py", line 186, in run
    best_model_path = self._train(
  File "train_bert.py", line 106, in _train
    outputs = self.model(inputs)
  File "/home/liuwei1/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liuwei1/AAGCN-ACSA/models/aagcn_bert.py", line 61, in forward
    x = F.relu(self.gc1(text_out, e_adj))
  File "/home/liuwei1/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liuwei1/AAGCN-ACSA/models/aagcn_bert.py", line 25, in forward
    hidden = torch.matmul(text, self.weight)
RuntimeError: mat1 dim 1 must match mat2 dim 0
```
Looking forward to your help, thanks

**Comment by BinLiang-NLP** [comment]
> If I use transformers instead of pytorch_pretrained_bert, there are something error:
> 
> ```python
> # aagcn_bert.py#56
> # encoder_layer, pooled_output = self.bert(
> #     text_bert_indices, token_type_ids=bert_segments_ids, output_all_encoded_layers=False)
>  output = self.bert(
>             text_bert_indices, token_type_ids=bert_segments_ids, return_dict=False)
>  text_out = output[0]
> ```
> 
> And the error is:
> 
> ```
> Traceback (most recent call last):
>   File "train_bert.py", line 338, in <module>
>     main()
>   File "train_bert.py", line 333, in main
>     ins.run()
>   File "train_bert.py", line 186, in run
>     best_model_path = self._train(
>   File "train_bert.py", line 106, in _train
>     outputs = self.model(inputs)
>   File "/home/liuwei1/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/liuwei1/AAGCN-ACSA/models/aagcn_bert.py", line 61, in forward
>     x = F.relu(self.gc1(text_out, e_adj))
>   File "/home/liuwei1/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/liuwei1/AAGCN-ACSA/models/aagcn_bert.py", line 25, in forward
>     hidden = torch.matmul(text, self.weight)
> RuntimeError: mat1 dim 1 must match mat2 dim 0
> ```
> 
> Looking forward to your help, thanks

Hi,
Do you mean you replace "pytorch_pretrained_bert" with "transformers", and then you get the above errors?

**Comment by shenjing023** [comment]
yes, and I notice you changed the "bert_dim" 1024 to 768 in train_bert.py, after I  followed the change, it works and no errors. Thanks again

**Comment by BinLiang-NLP** [comment]
> ```python
> output = self.bert(
>             text_bert_indices, token_type_ids=bert_segments_ids, return_dict=False)
>  text_out = output[0]
> ```

Hi,
Yes, I have changed the "bert_dim" to 768, and I can also run the code. There is no error.
Please let me know if there is any problem.
And I'm still trying to update the code of this repository. Please look forward to it!
Thanks a lot!!!
