### ISSUE TITLE
关于在REST14数据集上运行错误的问题

### ISSUE THREAD

**Issue by wll-best** [BinLiang-NLP/AAGCN-ACSA#7]
您好！感谢您分享的代码
我在您提供的semeval2014年数据集上运行时遇到了如下问题，不知道是怎么回事，15和16年的都能正常运行，唯独14年的出错了。希望您能解答一下，非常感谢！
![image](https://user-images.githubusercontent.com/62608056/147720119-24741929-d4f5-4f9a-90ee-b64c83fab285.png)

**Comment by BinLiang-NLP** [comment]
> 您好！感谢您分享的代码 我在您提供的semeval2014年数据集上运行时遇到了如下问题，不知道是怎么回事，15和16年的都能正常运行，唯独14年的出错了。希望您能解答一下，非常感谢！ ![image](https://user-images.githubusercontent.com/62608056/147720119-24741929-d4f5-4f9a-90ee-b64c83fab285.png)

您好！
非常感谢您提出的问题。
相关问题已修复。请使用“git pull"更新代码。
包括：train.py, train_bert.py, ./models/__init__.py, ./models/*14.py。
如有其他问题，请随时联系我。
谢谢！！！

**Comment by wll-best** [comment]
很感谢您的答复！没有问题啦
